# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invC <- function(M) {
    .Call(`_mypkgr_invC`, M)
}

#'mvnpdfoptimC
#'
#'@param x matrix x
#'@param mean column vector of x's mean
#'@param varcovM matrix of x's variance-covariance
#'@param Log boolean. If true, return log values of x's multivariate normal distribution
#'
#'@rdname mvnpdfoptimC
#'@export
#'
mvnpdfoptimC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfoptimC`, x, mean, varcovM, Log)
}

#'mvpdfsmartC
#'
#'@param x matrix x
#'@param mean column vector of x's mean
#'@param varcovM matrix of x's variance-covariance
#'@param Log boolean. If true, return log values of x's multivariate normal distribution
#'
#'@rdname mvnpdfsmartC
#'@export
#'
mvnpdfsmartC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_mypkgr_mvnpdfsmartC`, x, mean, varcovM, Log)
}

timesTwo <- function(x) {
    .Call(`_mypkgr_timesTwo`, x)
}

